/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.modulos;

import controlador.Controlador;

/**
 *
 * @author Julio
 */
public class modalHabitacion extends javax.swing.JDialog {

    /**
     * Creates new form modalHabitacion
     * @param parent
     * @param modal
     */
    public modalHabitacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnHabitacionReg.setActionCommand("RegistrarHabitacion");
        btnCancelarReg.setActionCommand("CancelarHabitacion");
        
    }
    
    public void setControlador(Controlador control){
        this.btnHabitacionReg.addActionListener(control);
        this.btnCancelarReg.addActionListener(control);
    }
    
    public void iniciar(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        habitaciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumHabitacion = new RSMaterialComponent.RSTextFieldOne();
        txtDescripcionHab = new RSMaterialComponent.RSTextFieldOne();
        txtPrecioHab = new RSMaterialComponent.RSTextFieldOne();
        cbTiposHabitacion = new RSMaterialComponent.RSComboBox();
        btnHabitacionReg = new newscomponents.RSButtonIcon_new();
        btnCancelarReg = new newscomponents.RSButtonIcon_new();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        habitaciones.setBackground(new java.awt.Color(255, 255, 255));
        habitaciones.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(35, 35, 35, 35), new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true)));
        habitaciones.setForeground(new java.awt.Color(51, 51, 51));
        habitaciones.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRANDO HABITACIÓN");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        habitaciones.add(jLabel1, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(61, 137, 248));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRECIO:");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        habitaciones.add(jLabel4, gridBagConstraints);

        jLabel7.setBackground(new java.awt.Color(61, 137, 248));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("N° DE HABITACIÓN:");
        jLabel7.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        habitaciones.add(jLabel7, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(61, 137, 248));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DESCRIPCIÓN:");
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        habitaciones.add(jLabel6, gridBagConstraints);

        jLabel8.setBackground(new java.awt.Color(61, 137, 248));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TIPO DE HABITACIÓN:");
        jLabel8.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        habitaciones.add(jLabel8, gridBagConstraints);

        txtNumHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumHabitacion.setBorderColor(new java.awt.Color(255, 255, 255));
        txtNumHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNumHabitacion.setPhColor(new java.awt.Color(0, 0, 0));
        txtNumHabitacion.setPlaceholder("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        habitaciones.add(txtNumHabitacion, gridBagConstraints);

        txtDescripcionHab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescripcionHab.setBorderColor(new java.awt.Color(255, 255, 255));
        txtDescripcionHab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDescripcionHab.setPhColor(new java.awt.Color(0, 0, 0));
        txtDescripcionHab.setPlaceholder("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        habitaciones.add(txtDescripcionHab, gridBagConstraints);

        txtPrecioHab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioHab.setBorderColor(new java.awt.Color(255, 255, 255));
        txtPrecioHab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrecioHab.setPhColor(new java.awt.Color(0, 0, 0));
        txtPrecioHab.setPlaceholder("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 15);
        habitaciones.add(txtPrecioHab, gridBagConstraints);

        cbTiposHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        cbTiposHabitacion.setColorArrow(new java.awt.Color(61, 137, 248));
        cbTiposHabitacion.setColorBorde(new java.awt.Color(255, 255, 255));
        cbTiposHabitacion.setColorFondo(new java.awt.Color(255, 255, 255));
        cbTiposHabitacion.setColorSeleccion(new java.awt.Color(61, 137, 248));
        cbTiposHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 15);
        habitaciones.add(cbTiposHabitacion, gridBagConstraints);

        btnHabitacionReg.setBackground(new java.awt.Color(61, 137, 248));
        btnHabitacionReg.setText("Registrar");
        btnHabitacionReg.setFocusPainted(false);
        btnHabitacionReg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHabitacionReg.setHideActionText(true);
        btnHabitacionReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHabitacionReg.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnHabitacionReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionRegActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 5);
        habitaciones.add(btnHabitacionReg, gridBagConstraints);

        btnCancelarReg.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelarReg.setText("Cancelar");
        btnCancelarReg.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnCancelarReg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarReg.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 15, 0);
        habitaciones.add(btnCancelarReg, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(habitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(habitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHabitacionRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionRegActionPerformed

    }//GEN-LAST:event_btnHabitacionRegActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(modalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(modalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(modalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(modalHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                modalHabitacion dialog = new modalHabitacion(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonIcon_new btnCancelarReg;
    public newscomponents.RSButtonIcon_new btnHabitacionReg;
    public RSMaterialComponent.RSComboBox cbTiposHabitacion;
    private javax.swing.JPanel habitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public RSMaterialComponent.RSTextFieldOne txtDescripcionHab;
    public RSMaterialComponent.RSTextFieldOne txtNumHabitacion;
    public RSMaterialComponent.RSTextFieldOne txtPrecioHab;
    // End of variables declaration//GEN-END:variables
}
