package vistas.modulos;

import controlador.Controlador;

public class VistaHabitacion extends javax.swing.JPanel {

    public VistaHabitacion() {
        initComponents();
        btnHabitacionReg.setActionCommand("RegistrarHabitacion");
        btnCancelarReg.setActionCommand("CancelarHabitacion");
    }
    
    public void setControlador(Controlador control){
        this.btnHabitacionReg.addActionListener(control);
        this.btnCancelarReg.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        habPanel = new javax.swing.JPanel();
        habitaciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumHabitacion = new RSMaterialComponent.RSTextFieldOne();
        txtDescripcionHan = new RSMaterialComponent.RSTextFieldOne();
        txtPrecioHab = new RSMaterialComponent.RSTextFieldOne();
        cbEstadosHab = new RSMaterialComponent.RSComboBox();
        cbTiposHabitacion = new RSMaterialComponent.RSComboBox();
        btnHabitacionReg = new newscomponents.RSButtonFlat_new();
        btnCancelarReg = new newscomponents.RSButtonFlat_new();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHabitacionReg = new RSMaterialComponent.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        habPanel.setBackground(new java.awt.Color(255, 255, 255));
        habPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(210, 214, 222)));
        habPanel.setAutoscrolls(true);
        habPanel.setLayout(new java.awt.BorderLayout());

        habitaciones.setBackground(new java.awt.Color(255, 255, 255));
        habitaciones.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(35, 35, 35, 35), new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true)));
        habitaciones.setForeground(new java.awt.Color(51, 51, 51));
        habitaciones.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRANDO HABITACIÓN");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        habitaciones.add(jLabel1, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(61, 137, 248));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRECIO:");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        habitaciones.add(jLabel4, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(61, 137, 248));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ESTADO:");
        jLabel5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        habitaciones.add(jLabel5, gridBagConstraints);

        jLabel7.setBackground(new java.awt.Color(61, 137, 248));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("N° DE HABITACIÓN:");
        jLabel7.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        habitaciones.add(jLabel7, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(61, 137, 248));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DESCRIPCIÓN:");
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        habitaciones.add(jLabel6, gridBagConstraints);

        jLabel8.setBackground(new java.awt.Color(61, 137, 248));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TIPO DE HABITACIÓN:");
        jLabel8.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        habitaciones.add(jLabel8, gridBagConstraints);

        txtNumHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumHabitacion.setBorderColor(new java.awt.Color(255, 255, 255));
        txtNumHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNumHabitacion.setPhColor(new java.awt.Color(0, 0, 0));
        txtNumHabitacion.setPlaceholder("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        habitaciones.add(txtNumHabitacion, gridBagConstraints);

        txtDescripcionHan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescripcionHan.setBorderColor(new java.awt.Color(255, 255, 255));
        txtDescripcionHan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDescripcionHan.setPhColor(new java.awt.Color(0, 0, 0));
        txtDescripcionHan.setPlaceholder("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        habitaciones.add(txtDescripcionHan, gridBagConstraints);

        txtPrecioHab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioHab.setBorderColor(new java.awt.Color(255, 255, 255));
        txtPrecioHab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrecioHab.setPhColor(new java.awt.Color(0, 0, 0));
        txtPrecioHab.setPlaceholder("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 15);
        habitaciones.add(txtPrecioHab, gridBagConstraints);

        cbEstadosHab.setForeground(new java.awt.Color(0, 0, 0));
        cbEstadosHab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DISPONIBLE", "OCUPADA", "RESERVADA", "MANTENIMIENTO" }));
        cbEstadosHab.setColorArrow(new java.awt.Color(61, 137, 248));
        cbEstadosHab.setColorBorde(new java.awt.Color(255, 255, 255));
        cbEstadosHab.setColorFondo(new java.awt.Color(255, 255, 255));
        cbEstadosHab.setColorSeleccion(new java.awt.Color(61, 137, 248));
        cbEstadosHab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 15);
        habitaciones.add(cbEstadosHab, gridBagConstraints);

        cbTiposHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        cbTiposHabitacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cbTiposHabitacion.setColorArrow(new java.awt.Color(61, 137, 248));
        cbTiposHabitacion.setColorBorde(new java.awt.Color(255, 255, 255));
        cbTiposHabitacion.setColorFondo(new java.awt.Color(255, 255, 255));
        cbTiposHabitacion.setColorSeleccion(new java.awt.Color(61, 137, 248));
        cbTiposHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 15);
        habitaciones.add(cbTiposHabitacion, gridBagConstraints);

        btnHabitacionReg.setBackground(new java.awt.Color(61, 137, 248));
        btnHabitacionReg.setText("Registrar");
        btnHabitacionReg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 5, 5);
        habitaciones.add(btnHabitacionReg, gridBagConstraints);

        btnCancelarReg.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelarReg.setText("Cancelar");
        btnCancelarReg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 5, 5, 0);
        habitaciones.add(btnCancelarReg, gridBagConstraints);

        habPanel.add(habitaciones, java.awt.BorderLayout.PAGE_START);

        tablaHabitacionReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Habitación", "Descripción", "Precio", "Tipo", "Disposición", "Editar", "Eliminar"
            }
        ));
        tablaHabitacionReg.setBackgoundHead(new java.awt.Color(61, 137, 248));
        tablaHabitacionReg.setBackgoundHover(new java.awt.Color(61, 137, 248));
        tablaHabitacionReg.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaHabitacionReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        tablaHabitacionReg.setFontHead(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaHabitacionReg.setFontRowHover(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        tablaHabitacionReg.setFontRowSelect(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        tablaHabitacionReg.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(tablaHabitacionReg);

        habPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(habPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 66));
        jLabel3.setText("Habitación / Registro de Habitaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonFlat_new btnCancelarReg;
    public newscomponents.RSButtonFlat_new btnHabitacionReg;
    public RSMaterialComponent.RSComboBox cbEstadosHab;
    public RSMaterialComponent.RSComboBox cbTiposHabitacion;
    public javax.swing.JPanel habPanel;
    private javax.swing.JPanel habitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSTableMetro tablaHabitacionReg;
    private RSMaterialComponent.RSTextFieldOne txtDescripcionHan;
    private RSMaterialComponent.RSTextFieldOne txtNumHabitacion;
    private RSMaterialComponent.RSTextFieldOne txtPrecioHab;
    // End of variables declaration//GEN-END:variables
}
