package vistas.modulos;

import controlador.Controlador;
import utilidades.TextPrompt;

public class VistaListadoRegistro extends javax.swing.JPanel {

    public VistaListadoRegistro() {
        initComponents();
        new TextPrompt("Buscar por fecha de entrada o salida", this.tfBusqueda);
    }
    
    public void setControlador(Controlador control){
        this.tfBusqueda.addKeyListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        habPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHabitaciones = new rojerusan.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        habPanel.setBackground(new java.awt.Color(255, 255, 255));
        habPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(210, 214, 222)));
        habPanel.setAutoscrolls(true);
        habPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setOpaque(false);

        tablaHabitaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        tablaHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id de Registro", "N° de Habitación", "Descripción", "Cliente", "Recepcionista", "Tipo", "Estado", "Fecha de Entrada", "Fecha de Salida", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHabitaciones.setAltoHead(30);
        tablaHabitaciones.setColorBackgoundHead(new java.awt.Color(249, 249, 249));
        tablaHabitaciones.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablaHabitaciones.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tablaHabitaciones.setColorFilasBackgound2(new java.awt.Color(249, 249, 249));
        tablaHabitaciones.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tablaHabitaciones.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tablaHabitaciones.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tablaHabitaciones.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tablaHabitaciones.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaHabitaciones.setFuenteFilas(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaHabitaciones.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tablaHabitaciones.setFuenteHead(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tablaHabitaciones.setGridColor(new java.awt.Color(255, 255, 255));
        tablaHabitaciones.setGrosorBordeFilas(0);
        tablaHabitaciones.setGrosorBordeHead(0);
        tablaHabitaciones.setMultipleSeleccion(false);
        tablaHabitaciones.setRowHeight(40);
        tablaHabitaciones.getTableHeader().setResizingAllowed(false);
        tablaHabitaciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaHabitaciones);
        if (tablaHabitaciones.getColumnModel().getColumnCount() > 0) {
            tablaHabitaciones.getColumnModel().getColumn(0).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaHabitaciones.getColumnModel().getColumn(1).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(1).setPreferredWidth(20);
            tablaHabitaciones.getColumnModel().getColumn(2).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(3).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(4).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(5).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(5).setPreferredWidth(10);
            tablaHabitaciones.getColumnModel().getColumn(6).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(6).setPreferredWidth(10);
            tablaHabitaciones.getColumnModel().getColumn(7).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(7).setPreferredWidth(10);
            tablaHabitaciones.getColumnModel().getColumn(8).setResizable(false);
            tablaHabitaciones.getColumnModel().getColumn(8).setPreferredWidth(10);
            tablaHabitaciones.getColumnModel().getColumn(9).setResizable(false);
        }

        habPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(habPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 66));
        jLabel3.setText("Habitación / Listado de Registros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        tfBusqueda.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        tfBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBusquedaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBusquedaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.weightx = 60.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 300);
        jPanel3.add(tfBusqueda, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_22px.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 14;
        jPanel3.add(jLabel1, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void tfBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBusquedaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBusquedaKeyPressed

    private void tfBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBusquedaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBusquedaKeyTyped
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel habPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public rojerusan.RSTableMetro tablaHabitaciones;
    public javax.swing.JTextField tfBusqueda;
    // End of variables declaration//GEN-END:variables
}
