package vistas.modulos;

import com.itextpdf.layout.borders.Border;
import controlador.Controlador;
import java.awt.Color;

public class VistaVentas extends javax.swing.JPanel {

    public VistaVentas() {
        initComponents();
        btnAddProducto.setActionCommand("agregarProducto");
        btnModProducto.setActionCommand("modificarProducto");
    }
    
    public void setControlador(Controlador control){
        btnAddProducto.addActionListener(control);
        btnModProducto.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAddProducto = new RSMaterialComponent.RSButtonMaterialOne();
        btnModProducto = new RSMaterialComponent.RSButtonMaterialOne();
        ventasPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 66));
        jLabel3.setText("Agregar ventas / Habitaciones ocupadas");

        btnAddProducto.setBackground(new java.awt.Color(61, 137, 248));
        btnAddProducto.setText("Agregar nuevo producto");
        btnAddProducto.setBackgroundHover(new java.awt.Color(0, 102, 204));
        btnAddProducto.setFocusPainted(false);
        btnAddProducto.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        btnModProducto.setBackground(new java.awt.Color(61, 137, 248));
        btnModProducto.setText("Detalles de producto");
        btnModProducto.setBackgroundHover(new java.awt.Color(0, 102, 204));
        btnModProducto.setFocusPainted(false);
        btnModProducto.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 620, Short.MAX_VALUE)
                .addComponent(btnAddProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(7, 7, 7))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        ventasPanel.setBackground(new java.awt.Color(255, 255, 255));
        ventasPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(210, 214, 222)));
        ventasPanel.setAutoscrolls(true);
        ventasPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));
        add(ventasPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSButtonMaterialOne btnAddProducto;
    public RSMaterialComponent.RSButtonMaterialOne btnModProducto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JPanel ventasPanel;
    // End of variables declaration//GEN-END:variables
}
