package vistas.modulos;

import com.itextpdf.layout.borders.Border;
import controlador.Controlador;
import java.awt.Color;

public class VistaAddVenta extends javax.swing.JPanel {

    public VistaAddVenta() {
        initComponents();  
        btnAddP.setActionCommand("addProductoV");
        btnAddRegistro.setActionCommand("addRegistroP");
    }
    
    public void setControlador(Controlador control){
        this.tbRegistroP.addMouseListener(control);
        this.btnAddP.addActionListener(control);
        this.tfCantidad.addKeyListener(control);
        this.tfPrecio.addKeyListener(control);
        this.btnAddRegistro.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        habPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbFechaOut = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbFechaIn = new javax.swing.JLabel();
        lbNumHab = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbTipoHab = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRegistroP = new rojerusan.RSTableMetro();
        jPanel5 = new javax.swing.JPanel();
        tfCantidad = new javax.swing.JTextField();
        lbProducto = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        cbProducto = new javax.swing.JComboBox<>();
        header2 = new javax.swing.JLabel();
        btnAddP = new newscomponents.RSButtonIcon_new();
        btnAddRegistro = new newscomponents.RSButtonIcon_new();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        habPanel.setBackground(new java.awt.Color(255, 255, 255));
        habPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(210, 214, 222)));
        habPanel.setAutoscrolls(true);
        habPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(35, 35, 35, 35), new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 1, true)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DETALLES DE HABITACIÓN");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(36, 51, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        lbFechaOut.setBackground(new java.awt.Color(255, 255, 255));
        lbFechaOut.setForeground(new java.awt.Color(51, 51, 51));
        lbFechaOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFechaOut.setText("-");
        lbFechaOut.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 36, 51);
        jPanel1.add(lbFechaOut, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRECIO:");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 292;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 51);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FECHA SALIDA");
        jLabel5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 255;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 51);
        jPanel1.add(jLabel5, gridBagConstraints);

        lbPrecio.setForeground(new java.awt.Color(51, 51, 51));
        lbPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecio.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 51);
        jPanel1.add(lbPrecio, gridBagConstraints);

        lbFechaIn.setBackground(new java.awt.Color(255, 255, 255));
        lbFechaIn.setForeground(new java.awt.Color(51, 51, 51));
        lbFechaIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFechaIn.setText("-");
        lbFechaIn.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 36, 0);
        jPanel1.add(lbFechaIn, gridBagConstraints);

        lbNumHab.setBackground(new java.awt.Color(255, 255, 255));
        lbNumHab.setForeground(new java.awt.Color(51, 51, 51));
        lbNumHab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumHab.setText("-");
        lbNumHab.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 51, 0, 0);
        jPanel1.add(lbNumHab, gridBagConstraints);

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("N° DE HABITACIÓN:");
        jLabel7.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 287;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 51, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CLIENTE");
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 353;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 51, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TIPO DE HABITACIÓN:");
        jLabel8.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 287;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        lbTipoHab.setForeground(new java.awt.Color(51, 51, 51));
        lbTipoHab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTipoHab.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(lbTipoHab, gridBagConstraints);

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CLIENTE");
        jLabel9.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 353;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 51, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FECHA ENTRADA");
        jLabel10.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 317;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        lbCliente.setBackground(new java.awt.Color(255, 255, 255));
        lbCliente.setForeground(new java.awt.Color(51, 51, 51));
        lbCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCliente.setText("-");
        lbCliente.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 51, 36, 0);
        jPanel1.add(lbCliente, gridBagConstraints);

        habPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setOpaque(false);

        tbRegistroP.setBackground(new java.awt.Color(255, 255, 255));
        tbRegistroP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        tbRegistroP.setForeground(new java.awt.Color(255, 255, 255));
        tbRegistroP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Subtotal", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRegistroP.setAltoHead(30);
        tbRegistroP.setColorBackgoundHead(new java.awt.Color(249, 249, 249));
        tbRegistroP.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tbRegistroP.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tbRegistroP.setColorFilasBackgound2(new java.awt.Color(249, 249, 249));
        tbRegistroP.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tbRegistroP.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tbRegistroP.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tbRegistroP.setColorSelBackgound(new java.awt.Color(240, 240, 240));
        tbRegistroP.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tbRegistroP.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tbRegistroP.setFuenteFilas(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tbRegistroP.setFuenteFilasSelect(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        tbRegistroP.setFuenteHead(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tbRegistroP.setGridColor(new java.awt.Color(255, 255, 255));
        tbRegistroP.setGrosorBordeFilas(0);
        tbRegistroP.setGrosorBordeHead(0);
        tbRegistroP.setMultipleSeleccion(false);
        tbRegistroP.setRowHeight(40);
        tbRegistroP.getTableHeader().setResizingAllowed(false);
        tbRegistroP.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbRegistroP);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        tfCantidad.setBackground(new java.awt.Color(255, 255, 255));
        tfCantidad.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfCantidad.setForeground(new java.awt.Color(0, 0, 0));
        tfCantidad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        tfCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCantidadActionPerformed(evt);
            }
        });
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 50);
        jPanel5.add(tfCantidad, gridBagConstraints);

        lbProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbProducto.setForeground(new java.awt.Color(102, 102, 102));
        lbProducto.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jPanel5.add(lbProducto, gridBagConstraints);

        header1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        header1.setForeground(new java.awt.Color(102, 102, 102));
        header1.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 20.0;
        jPanel5.add(header1, gridBagConstraints);

        tfPrecio.setEditable(false);
        tfPrecio.setBackground(new java.awt.Color(255, 255, 255));
        tfPrecio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfPrecio.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        tfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecioActionPerformed(evt);
            }
        });
        tfPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        jPanel5.add(tfPrecio, gridBagConstraints);

        cbProducto.setBackground(new java.awt.Color(255, 255, 255));
        cbProducto.setForeground(new java.awt.Color(102, 102, 102));
        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbProducto.setFocusable(false);
        cbProducto.setLightWeightPopupEnabled(false);
        cbProducto.setRequestFocusEnabled(false);
        cbProducto.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 10, 50);
        jPanel5.add(cbProducto, gridBagConstraints);

        header2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        header2.setForeground(new java.awt.Color(102, 102, 102));
        header2.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 20.0;
        jPanel5.add(header2, gridBagConstraints);

        btnAddP.setBackground(new java.awt.Color(61, 137, 248));
        btnAddP.setText("Agregar a la venta");
        btnAddP.setFocusPainted(false);
        btnAddP.setHideActionText(true);
        btnAddP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddP.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnAddP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        jPanel5.add(btnAddP, gridBagConstraints);

        btnAddRegistro.setBackground(new java.awt.Color(61, 137, 248));
        btnAddRegistro.setText("Guardar registro");
        btnAddRegistro.setFocusPainted(false);
        btnAddRegistro.setHideActionText(true);
        btnAddRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddRegistro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_CART);
        btnAddRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRegistroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        jPanel5.add(btnAddRegistro, gridBagConstraints);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        habPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(habPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 53, 66));
        jLabel3.setText("Recepción / Registro de Habitaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCantidadActionPerformed

    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
        char val = evt.getKeyChar();
        if(val < '0' || val > '9'){
            evt.consume();}
    }//GEN-LAST:event_tfCantidadKeyTyped

    private void tfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecioActionPerformed

    private void tfPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecioKeyTyped

    private void btnAddPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPActionPerformed

    private void btnAddRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRegistroActionPerformed
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public newscomponents.RSButtonIcon_new btnAddP;
    public newscomponents.RSButtonIcon_new btnAddRegistro;
    public javax.swing.JComboBox<String> cbProducto;
    public javax.swing.JPanel habPanel;
    public javax.swing.JLabel header1;
    public javax.swing.JLabel header2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbCliente;
    public javax.swing.JLabel lbFechaIn;
    public javax.swing.JLabel lbFechaOut;
    public javax.swing.JLabel lbNumHab;
    public javax.swing.JLabel lbPrecio;
    public javax.swing.JLabel lbProducto;
    public javax.swing.JLabel lbTipoHab;
    public rojerusan.RSTableMetro tbRegistroP;
    public javax.swing.JTextField tfCantidad;
    public javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
